package testbed;
// Generated by makedfa
public interface IEditorScript {
static final int
 T_WS = 256,
 T_BROP = 257,
 T_BRCL = 258,
 T_PAROP = 259,
 T_PARCL = 260,
 T_INT = 261,
 T_DBL = 262,
 T_LBL = 263,
 T_BOOL = 264,
 T_WORD = 265;


}
